### ISSUE TITLE
Terraform parser not working on OSX and Linux

### ISSUE THREAD

**Issue by villanisaac-kr** [TheCloudTheory/arm-estimator#206]
When running locally either using the binary or the docker image I get below error where it can't find the library "libace-terraform-parser-linux.dll"

docker run -e AZURE_CLIENT_ID=$ARM_CLIENT_ID -e AZURE_TENANT_ID=$ARM_TENANT_ID -e AZURE_CLIENT_SECRET=$ARM_CLIENT_SECRET -v .:/app/templates thecloudtheory/azure-cost-estimator templates/terraform.tf $ARM_SUBSCRIPTION_ID [ Redacted ]
                                                                                                   
                                              .***      ***                                         
                                   ,    ***.********,****                                           
                                     **********************                                         
                               *    ************. ***********  *                                    
                             ///   *******, ****  ////////////******                                
                               .//************ ///// /////////********                              
                           ///////// ********///////// //////.********    (,                        
                     .   ///////////// **** ////////////,////******* ( (/                           
                       *////////////////   ////////////////  ** ((((((((((((                        
                        ///,  */////////.   **************,    ((((((((((((((                       
                       ///////////////.(((((((,******** ///// (((((( (((((((((                      
                       ///////////// ((((((((((((   ////////// ((((((((((*((((                      
                        ////////// ((((((((((( ((    //////////(((((((((((((((                      
                    //   /////// (((((( (((((((((((((((( ///////(((((((((((((                       
                       //   /  ( ((((((((((((((((,((((((((((.////(((((((((  ((                      
                                                                                                    
                                  ACE (Azure Cost Estimator) [1.2.0]

General help: https://github.com/TheCloudTheory/arm-estimator/discussions
Bugs & issues: https://github.com/TheCloudTheory/arm-estimator/issues

------------------------------

Run configuration:

-> Scope: ResourceGroup
-> Susbcription Id: [Redacted]
-> Resource group: [Redactoed]
-> Template file: templates/terraform.tf
-> Deployment mode: Incremental
-> Threshold: Not Set
-> Parameters file: Not Set
-> Currency: USD
-> Generate JSON output: False
-> Silent mode: False
-> Redirect stdout: False
-> Disabled detailed metrics: False
-> Generate HTML output: False
-> HTML output filename: Not Set
-> Dry run enabled: False
-> Cache disabled: False

------------------------------

Starting parsing using embedded Go parser.
Unhandled exception: System.DllNotFoundException: Unable to load shared library 'ace-terraform-parser-linux.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libace-terraform-parser-linux.dll: cannot open shared object file: No such file or directory
   at ACE.Compilation.TerraformCompiler.GenerateParsedPlan(GoString workingDir, GoString planFile)
   at ACE.Compilation.TerraformCompiler.Compile(FileInfo templateFile) in /src/ace/Compilation/TerraformCompiler.cs:line 52
   at ACE.Compilation.TemplateCompiler.Compile() in /src/ace/Compilation/TemplateCompiler.cs:line 40
   at ACE.Program.GetTemplate(FileInfo templateFile, ILogger`1 logger, TemplateType& templateType) in /src/ace/Program.cs:line 317
   at ACE.Program.Estimate(FileInfo templateFile, String scopeId, String resourceGroupName, String location, EstimateOptions options, CommandType commandType) in /src/ace/Program.cs:line 216
   at ACE.Program.<>c.<<Main>b__1_15>d.MoveNext() in /src/ace/Program.cs:line 64
--- End of stack trace from previous location ---
   at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()

**Comment by kamil-mrzyglod** [comment]
Seems like something may be off with the package. Let me check if the published artifact contain all the dependencies.

**Comment by kamil-mrzyglod** [comment]
@villanisaac-kr quick question - in the title you stated, that it's not working for OSX. I believe you have that OS and tries to run ACE from a binary and via Docker, is that correct?

**Comment by villanisaac-kr** [comment]
> @villanisaac-kr quick question - in the title you stated, that it's not working for OSX. I believe you have that OS and tries to run ACE from a binary and via Docker, is that correct?

Yes I'm using OSX. I thought that by using  the Docker image all the libraries would've been included. But just got the same missing library.

**Comment by kamil-mrzyglod** [comment]
@villanisaac-kr Could you please check the latest binary for OSX from here? https://github.com/TheCloudTheory/arm-estimator/releases/tag/1.2.1 

I believe the problem may have been caused by missing OSX binary for Terraform parser. Regarding Docker I need to dive deeper into that as for now I cannot reproduce it.
