### ISSUE TITLE
Allow to run reusable workflow without required parameters file

### ISSUE THREAD

**Issue by kamil-mrzyglod** [TheCloudTheory/arm-estimator#223]
Relates #214

**Comment by BenjaminEngeset** [comment]
@kamil-mrzyglod Are you able to prioritize this one? If not, I'd be willing to give a try and create the PR.

**Comment by kamil-mrzyglod** [comment]
Feel free to give it a try. I'll be able to work on that not sooner than Thursday / Friday.

**Comment by BenjaminEngeset** [comment]
@kamil-mrzyglod I have been tinkering with this, but currently facing an issue I fully cannot understand. Perhaps you could enlighten me.

```
 cost-estimate:
    uses: BenjaminEngeset/arm-estimator/.github/workflows/estimateFromUrl.yml@benjaminengeset/fix-costestimate-fromurl-workflow
    needs: [get-module-to-deploy, deployment-test-prereq]
    if: needs.get-module-to-deploy.outputs.module_dir
    permissions:
      id-token: write
      contents: read
    with:
      rg: ${{ needs.deployment-test-prereq.outputs.rg_name }}
      environment: ''
      templateFileURL: https://raw.githubusercontent.com/{placeholder}/{placeholder}/${{ github.event_name == 'pull_request' && github.head_ref || github.ref_name }}/${{ needs.get-module-to-deploy.outputs.module_dir }}/test/main.test.json
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID_BRM_DEPLOYMENT_TEST_RG }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID_T_PLATFORM_001 }}
```
The reusable workflow:
```
jobs:
  Estimate:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
    - uses: robinraju/release-downloader@v1.5
      name: Download Arm-Estimator release
      id: downloadACE
      with:
        repository: "TheCloudTheory/arm-estimator"
        #We can't use the latest flag when the releases are marked as pre-release. IE. Https://api.github.com/repos/TheCloudTheory/arm-estimator/releases/latest comes back 404
        #latest: ${{ inputs.aceVersion == 'latest' }}
        #tag: ${{ (inputs.aceVersion != 'latest' && inputs.aceVersion) || '' }}
        tag: ${{ inputs.aceVersion }}
        fileName: "linux-x64.zip"
        
    - name: Unzip and prepare ACE
      run: |
        echo ${{steps.downloadACE.outputs.tag_name}}
        ACEZIP="linux-x64.zip"
        echo $ACEZIP
        unzip $ACEZIP
        chmod +x ./azure-cost-estimator

    - uses: azure/login@v1.4.6
      name: Login to Azure
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
    - name: Prepare/Check Arm Assets
      id: armassets
      env:
        templateURL: ${{ inputs.templateFileURL }}
        paramsURL: ${{ inputs.templateParamFileURL }}
      run: |
        if [ ! -z $paramsURL ]; then
          echo "Downloading arm template"
          curl -O $templateURL -L

          echo "Downloading param file"
          curl -O $paramsURL -L

          ls -l

          echo "template=${templateURL##*/}" >> $GITHUB_OUTPUT
          echo "params=${paramsURL##*/}" >> $GITHUB_OUTPUT
          else
            echo "Downloading arm template"
            curl -O $templateURL -L

            ls -l

            echo "template=${templateURL##*/}" >> $GITHUB_OUTPUT
          fi
  
    - name: Estimate
      id: ace
      env:
        templateParams: ${{ inputs.templateParams }}
      run: |             
        if [ ! -z "$templateParams" ]
        then 
          templateParamsInlined=$(echo --inline ${templateParams//[' ']/ --inline })
        fi

        ls
        
        if [ ! -z ${{ steps.armassets.outputs.params }} ]
        then
          echo "Estimating template ${{ steps.armassets.outputs.template }} with params file ${{ steps.armassets.outputs.params }} and inline params $templateParamsInlined - deploying into rg ${{ inputs.rg }}"
          ./azure-cost-estimator ${{ steps.armassets.outputs.template }} ${{ secrets.AZURE_SUBSCRIPTION_ID }} ${{ inputs.rg }} --parameters ${{ steps.armassets.outputs.params }} $templateParamsInlined --generateJsonOutput --jsonOutputFilename estimate
        else

        ${{ steps.armassets.outputs.template }} | jq .

        echo "Estimating template ${{ steps.armassets.outputs.template }} with inline params $templateParamsInlined - deploying into rg ${{ inputs.rg }}"
        ./azure-cost-estimator ${{ steps.armassets.outputs.template }} ${{ secrets.AZURE_SUBSCRIPTION_ID }} ${{ inputs.rg }} $templateParamsInlined --generateJsonOutput --jsonOutputFilename estimate
        fi

        ls
```

Log:
```
2023-11-22T09:03:46.6031469Z Image: ubuntu-22.04
2023-11-22T09:03:46.6031983Z Version: 20231115.7.0
2023-11-22T09:03:46.6033250Z Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20231115.7/images/ubuntu/Ubuntu2204-Readme.md
2023-11-22T09:03:46.6034927Z Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20231115.7
2023-11-22T09:03:46.6036027Z ##[endgroup]
2023-11-22T09:03:46.6037050Z ##[group]Runner Image Provisioner
2023-11-22T09:03:46.6037667Z 2.0.321.1
2023-11-22T09:03:46.6038158Z ##[endgroup]
2023-11-22T09:03:46.6039241Z ##[group]GITHUB_TOKEN Permissions
2023-11-22T09:03:46.6041406Z Contents: read
2023-11-22T09:03:46.6041915Z Metadata: read
2023-11-22T09:03:46.6042571Z ##[endgroup]
2023-11-22T09:03:46.6046766Z Secret source: Actions
2023-11-22T09:03:46.6047445Z Prepare workflow directory
2023-11-22T09:03:46.6828900Z Prepare all required actions
2023-11-22T09:03:46.7021194Z Getting action download info
2023-11-22T09:03:47.0168480Z Download action repository 'robinraju/release-downloader@v1.5' (SHA:d5673a24e65c6d286599c0ac7019805d32e15c0b)
2023-11-22T09:03:47.6849019Z Download action repository 'azure/login@v1.4.6' (SHA:92a5484dfaf04ca78a94597f4f19fea633851fa2)
2023-11-22T09:03:52.2948059Z Download action repository 'actions/upload-artifact@v3.1.2' (SHA:0b7f8abb1508181956e8e162db84b466c27e18ce)
2023-11-22T09:03:52.4605134Z Uses: BenjaminEngeset/arm-estimator/.github/workflows/estimateFromUrl.yml@refs/heads/benjaminengeset/fix-costestimate-fromurl-workflow (f92406331b16b9c9380f562f46439ca8f31434f7)
2023-11-22T09:03:52.4607934Z ##[group] Inputs
2023-11-22T09:03:52.4608319Z   environment: 
2023-11-22T09:03:52.4608646Z   rg: rg-60c74c3-test-we-001
2023-11-22T09:03:52.4609034Z   aceVersion: 1.3
2023-11-22T09:03:52.4610272Z   templateFileURL: https://raw.githubusercontent.com/xxx/xxx/benjaminengeset/test-module/modules/operationalinsights/workspaces/test/main.test.json
2023-11-22T09:03:52.4611605Z   templateParamFileURL: 
2023-11-22T09:03:52.4611975Z   templateParams: 
2023-11-22T09:03:52.4612304Z ##[endgroup]
2023-11-22T09:03:52.4612873Z Complete job name: cost-estimate / Estimate
2023-11-22T09:03:52.5786687Z ##[group]Run robinraju/release-downloader@v1.5
2023-11-22T09:03:52.5787233Z with:
2023-11-22T09:03:52.5787570Z   repository: TheCloudTheory/arm-estimator
2023-11-22T09:03:52.5788023Z   tag: 1.3
2023-11-22T09:03:52.5788300Z   fileName: linux-x64.zip
2023-11-22T09:03:52.5788650Z   latest: false
2023-11-22T09:03:52.5788953Z   tarBall: false
2023-11-22T09:03:52.5789250Z   zipBall: false
2023-11-22T09:03:52.5789555Z   out-file-path: .
2023-11-22T09:03:52.5790146Z   token: ***
2023-11-22T09:03:52.5790524Z   github-api-url: https://api.github.com
2023-11-22T09:03:52.5790985Z ##[endgroup]
2023-11-22T09:03:52.7552372Z Fetching release 1.3 from repo TheCloudTheory/arm-estimator
2023-11-22T09:03:53.0167889Z Found release tag: 1.3
2023-11-22T09:03:53.0168221Z 
2023-11-22T09:03:53.0224342Z ##[warning]The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
2023-11-22T09:03:53.0252653Z Downloading file: linux-x64.zip to: /home/runner/work/bicep-registry-modules-test/bicep-registry-modules-test
2023-11-22T09:03:53.7487718Z Done: /home/runner/work/bicep-registry-modules-test/bicep-registry-modules-test/linux-x64.zip
2023-11-22T09:03:53.7811353Z ##[group]Run echo 1.3
2023-11-22T09:03:53.7811821Z [36;1mecho 1.3[0m
2023-11-22T09:03:53.7812172Z [36;1mACEZIP="linux-x64.zip"[0m
2023-11-22T09:03:53.7812571Z [36;1mecho $ACEZIP[0m
2023-11-22T09:03:53.7812908Z [36;1munzip $ACEZIP[0m
2023-11-22T09:03:53.7813550Z [36;1mchmod +x ./azure-cost-estimator[0m
2023-11-22T09:03:53.7883773Z shell: /usr/bin/bash -e {0}
2023-11-22T09:03:53.7884236Z ##[endgroup]
2023-11-22T09:03:53.8049576Z 1.3
2023-11-22T09:03:53.8051270Z linux-x64.zip
2023-11-22T09:03:53.8074153Z Archive:  linux-x64.zip
2023-11-22T09:03:53.8678149Z   inflating: ace-terraform-parser-linux.dll  
2023-11-22T09:03:53.9253464Z   inflating: ace-terraform-parser-macos.dll  
2023-11-22T09:03:54.0162192Z   inflating: ace-terraform-parser-windows.dll  
2023-11-22T09:03:54.0178836Z   inflating: azure-cost-estimator.pdb  
2023-11-22T09:03:54.7795935Z   inflating: azure-cost-estimator    
2023-11-22T09:03:54.7815012Z    creating: Html/
2023-11-22T09:03:54.7826031Z   inflating: Html/GeneratorTemplate.html  
2023-11-22T09:03:54.7886684Z ##[group]Run azure/login@v1.4.6
2023-11-22T09:03:54.7887078Z with:
2023-11-22T09:03:54.7887758Z   client-id: ***
2023-11-22T09:03:54.7888157Z   tenant-id: ***
2023-11-22T09:03:54.7888581Z   subscription-id: ***
2023-11-22T09:03:54.7888954Z   enable-AzPSSession: false
2023-11-22T09:03:54.7889331Z   environment: azurecloud
2023-11-22T09:03:54.7889699Z   allow-no-subscriptions: false
2023-11-22T09:03:54.7890141Z   audience: api://AzureADTokenExchange
2023-11-22T09:03:54.7890577Z ##[endgroup]
2023-11-22T09:03:59.0808150Z Using OIDC authentication...
2023-11-22T09:03:59.2761728Z Federated token details: 
2023-11-22T09:03:59.2762827Z  issuer - https://token.actions.githubusercontent.com 
2023-11-22T09:03:59.2763940Z  subject claim - repo:xxx/xxx:pull_request
2023-11-22T09:03:59.2764921Z [command]/usr/bin/az cloud set -n azurecloud
2023-11-22T09:04:08.6878048Z Done setting cloud: "azurecloud"
2023-11-22T09:04:10.4386948Z Login successful.
2023-11-22T09:04:10.4542635Z ##[group]Run if [ ! -z $paramsURL ]; then
2023-11-22T09:04:10.4543243Z [36;1mif [ ! -z $paramsURL ]; then[0m
2023-11-22T09:04:10.4543739Z [36;1m  echo "Downloading arm template"[0m
2023-11-22T09:04:10.4544226Z [36;1m  curl -O $templateURL -L[0m
2023-11-22T09:04:10.4544640Z [36;1m[0m
2023-11-22T09:04:10.4544967Z [36;1m  echo "Downloading param file"[0m
2023-11-22T09:04:10.4545434Z [36;1m  curl -O $paramsURL -L[0m
2023-11-22T09:04:10.4545813Z [36;1m[0m
2023-11-22T09:04:10.4546080Z [36;1m  ls -l[0m
2023-11-22T09:04:10.4546367Z [36;1m[0m
2023-11-22T09:04:10.4546796Z [36;1m  echo "template=${templateURL##*/}" >> $GITHUB_OUTPUT[0m
2023-11-22T09:04:10.4547456Z [36;1m  echo "params=${paramsURL##*/}" >> $GITHUB_OUTPUT[0m
2023-11-22T09:04:10.4547961Z [36;1m  else[0m
2023-11-22T09:04:10.4548325Z [36;1m    echo "Downloading arm template"[0m
2023-11-22T09:04:10.4548806Z [36;1m    curl -O $templateURL -L[0m
2023-11-22T09:04:10.4549209Z [36;1m[0m
2023-11-22T09:04:10.4549506Z [36;1m    ls -l[0m
2023-11-22T09:04:10.4549809Z [36;1m[0m
2023-11-22T09:04:10.4550229Z [36;1m    echo "template=${templateURL##*/}" >> $GITHUB_OUTPUT[0m
2023-11-22T09:04:10.4550768Z [36;1m  fi[0m
2023-11-22T09:04:10.4602042Z shell: /usr/bin/bash -e {0}
2023-11-22T09:04:10.4602447Z env:
2023-11-22T09:04:10.4602730Z   AZURE_HTTP_USER_AGENT: 
2023-11-22T09:04:10.4603109Z   AZUREPS_HOST_ENVIRONMENT: 
2023-11-22T09:04:10.4604402Z   templateURL: https://raw.githubusercontent.com/xxx/xxx/benjaminengeset/test-module/modules/operationalinsights/workspaces/test/main.test.json
2023-11-22T09:04:10.4605677Z   paramsURL: 
2023-11-22T09:04:10.4605968Z ##[endgroup]
2023-11-22T09:04:10.4682793Z Downloading arm template
2023-11-22T09:04:10.4756489Z   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
2023-11-22T09:04:10.4757604Z                                  Dload  Upload   Total   Spent    Left  Speed
2023-11-22T09:04:10.4759121Z 
2023-11-22T09:04:10.6965099Z   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
2023-11-22T09:04:10.6966306Z 100    14  100    14    0     0     63      0 --:--:-- --:--:-- --:--:--    63
2023-11-22T09:04:10.7002603Z total 130748
2023-11-22T09:04:10.7003690Z drwxr-xr-x 2 runner docker     4096 Nov  9 20:22 Html
2023-11-22T09:04:10.7004783Z -rw-r--r-- 1 runner docker  5746112 Nov  9 20:22 ace-terraform-parser-linux.dll
2023-11-22T09:04:10.7012545Z -rw-r--r-- 1 runner docker  5660064 Nov  9 20:22 ace-terraform-parser-macos.dll
2023-11-22T09:04:10.7013672Z -rw-r--r-- 1 runner docker  9356135 Nov  9 20:22 ace-terraform-parser-windows.dll
2023-11-22T09:04:10.7014746Z -rwxr-xr-x 1 runner docker 72527296 Nov  9 20:22 azure-cost-estimator
2023-11-22T09:04:10.7016135Z -rw-r--r-- 1 runner docker   116336 Nov  9 20:22 azure-cost-estimator.pdb
2023-11-22T09:04:10.7017011Z -rw-r--r-- 1 runner docker 40463360 Nov 22 09:03 linux-x64.zip
2023-11-22T09:04:10.7017781Z -rw-r--r-- 1 runner docker       14 Nov 22 09:04 main.test.json
2023-11-22T09:04:10.7054204Z ##[group]Run if [ ! -z "$templateParams" ]
2023-11-22T09:04:10.7054776Z [36;1mif [ ! -z "$templateParams" ][0m
2023-11-22T09:04:10.7055214Z [36;1mthen [0m
2023-11-22T09:04:10.7055804Z [36;1m  templateParamsInlined=$(echo --inline ${templateParams//[' ']/ --inline })[0m
2023-11-22T09:04:10.7056500Z [36;1mfi[0m
2023-11-22T09:04:10.7056787Z [36;1m[0m
2023-11-22T09:04:10.7057047Z [36;1mls[0m
2023-11-22T09:04:10.7057315Z [36;1m[0m
2023-11-22T09:04:10.7057582Z [36;1mif [ ! -z  ][0m
2023-11-22T09:04:10.7057912Z [36;1mthen[0m
2023-11-22T09:04:10.7058879Z [36;1m  echo "Estimating template main.test.json with params file  and inline params $templateParamsInlined - deploying into rg rg-60c74c3-test-we-001"[0m
2023-11-22T09:04:10.7060933Z [36;1m  ./azure-cost-estimator main.test.json *** rg-60c74c3-test-we-001 --parameters  $templateParamsInlined --generateJsonOutput --jsonOutputFilename estimate[0m
2023-11-22T09:04:10.7062157Z [36;1melse[0m
2023-11-22T09:04:10.7062497Z [36;1m[0m
2023-11-22T09:04:10.7062799Z [36;1mmain.test.json | jq .[0m
2023-11-22T09:04:10.7063184Z [36;1m[0m
2023-11-22T09:04:10.7064033Z [36;1mecho "Estimating template main.test.json with inline params $templateParamsInlined - deploying into rg rg-60c74c3-test-we-001"[0m
2023-11-22T09:04:10.7065873Z [36;1m./azure-cost-estimator main.test.json *** rg-60c74c3-test-we-001 $templateParamsInlined --generateJsonOutput --jsonOutputFilename estimate[0m
2023-11-22T09:04:10.7066908Z [36;1mfi[0m
2023-11-22T09:04:10.7067187Z [36;1m[0m
2023-11-22T09:04:10.7067450Z [36;1mls[0m
2023-11-22T09:04:10.7118032Z shell: /usr/bin/bash -e {0}
2023-11-22T09:04:10.7118599Z env:
2023-11-22T09:04:10.7118888Z   AZURE_HTTP_USER_AGENT: 
2023-11-22T09:04:10.7119275Z   AZUREPS_HOST_ENVIRONMENT: 
2023-11-22T09:04:10.7119656Z   templateParams: 
2023-11-22T09:04:10.7119978Z ##[endgroup]
2023-11-22T09:04:10.7207175Z Html
2023-11-22T09:04:10.7208022Z ace-terraform-parser-linux.dll
2023-11-22T09:04:10.7209060Z ace-terraform-parser-macos.dll
2023-11-22T09:04:10.7209644Z ace-terraform-parser-windows.dll
2023-11-22T09:04:10.7210100Z azure-cost-estimator
2023-11-22T09:04:10.7210484Z azure-cost-estimator.pdb
2023-11-22T09:04:10.7210869Z linux-x64.zip
2023-11-22T09:04:10.7211175Z main.test.json
2023-11-22T09:04:10.7217683Z /home/runner/work/_temp/9867f5c0-6a85-4c62-a37c-2b74f0f6a4aa.sh: line 14: main.test.json: command not found
2023-11-22T09:04:10.7474900Z Estimating template main.test.json with inline params  - deploying into rg rg-60c74c3-test-we-001
2023-11-22T09:04:10.9832812Z                                                                                                    
2023-11-22T09:04:10.9833534Z                                               .***      ***                                         
2023-11-22T09:04:10.9834177Z                                    ,    ***.********,****                                           
2023-11-22T09:04:10.9834812Z                                      **********************                                         
2023-11-22T09:04:10.9835418Z                                *    ************. ***********  *                                    
2023-11-22T09:04:10.9836033Z                              ///   *******, ****  ////////////******                                
2023-11-22T09:04:10.9837117Z                                .//************ ///// /////////********                              
2023-11-22T09:04:10.9837761Z                            ///////// ********///////// //////.********    (,                        
2023-11-22T09:04:10.9838416Z                      .   ///////////// **** ////////////,////******* ( (/                           
2023-11-22T09:04:10.9839081Z                        *////////////////   ////////////////  ** ((((((((((((                        
2023-11-22T09:04:10.9857973Z                         ///,  */////////.   **************,    ((((((((((((((                       
2023-11-22T09:04:10.9858892Z                        ///////////////.(((((((,******** ///// (((((( (((((((((                      
2023-11-22T09:04:10.9859530Z                        ///////////// ((((((((((((   ////////// ((((((((((*((((                      
2023-11-22T09:04:10.9860166Z                         ////////// ((((((((((( ((    //////////(((((((((((((((                      
2023-11-22T09:04:10.9860806Z                     //   /////// (((((( (((((((((((((((( ///////(((((((((((((                       
2023-11-22T09:04:10.9861428Z                        //   /  ( ((((((((((((((((,((((((((((.////(((((((((  ((                      
2023-11-22T09:04:10.9862032Z                                                                                                     
2023-11-22T09:04:10.9862637Z                                   ACE (Azure Cost Estimator) [1.3]
2023-11-22T09:04:10.9863019Z 
2023-11-22T09:04:10.9863597Z General help: https://github.com/TheCloudTheory/arm-estimator/discussions
2023-11-22T09:04:10.9864494Z Bugs & issues: https://github.com/TheCloudTheory/arm-estimator/issues
2023-11-22T09:04:10.9864979Z 
2023-11-22T09:04:10.9865149Z ------------------------------
2023-11-22T09:04:10.9865398Z 
2023-11-22T09:04:10.9865557Z Run configuration:
2023-11-22T09:04:10.9865766Z 
2023-11-22T09:04:10.9865940Z -> Scope: ResourceGroup
2023-11-22T09:04:10.9866556Z -> Susbcription Id: ***
2023-11-22T09:04:10.9867000Z -> Resource group: rg-60c74c3-test-we-001
2023-11-22T09:04:10.9867501Z -> Template file: main.test.json
2023-11-22T09:04:10.9867952Z -> Deployment mode: Incremental
2023-11-22T09:04:10.9868374Z -> Threshold: Not Set
2023-11-22T09:04:10.9868752Z -> Parameters file: Not Set
2023-11-22T09:04:10.9869132Z -> Currency: USD
2023-11-22T09:04:10.9869493Z -> Generate JSON output: True
2023-11-22T09:04:10.9869911Z -> Silent mode: False
2023-11-22T09:04:10.9870297Z -> Redirect stdout: False
2023-11-22T09:04:10.9870722Z -> Disabled detailed metrics: False
2023-11-22T09:04:10.9871193Z -> Generate HTML output: False
2023-11-22T09:04:10.9871637Z -> HTML output filename: Not Set
2023-11-22T09:04:10.9872087Z -> Dry run enabled: False
2023-11-22T09:04:10.9872481Z -> Cache disabled: False
2023-11-22T09:04:10.9872865Z -> Cache handler: Local
2023-11-22T09:04:10.9873240Z -> Conversion rate: 1
2023-11-22T09:04:10.9873599Z -> Webhook URL: Disabled
2023-11-22T09:04:10.9873899Z 
2023-11-22T09:04:10.9874045Z ------------------------------
2023-11-22T09:04:10.9874300Z 
2023-11-22T09:04:11.0176510Z [Error] Couldn't parse the following template - 404:NotFound. Error: ':' is an invalid end of a number. Expected a delimiter. Path: $ | LineNumber: 0 | BytePositionInLine: 3.
2023-11-22T09:04:11.0285733Z Unhandled exception: System.Exception: Exception of type 'System.Exception' was thrown.
2023-11-22T09:04:11.0287152Z    at ACE.Program.<>c.<<Main>b__2_22>d.MoveNext() in /home/runner/work/arm-estimator/arm-estimator/arm-estimator/Program.cs:line 88
2023-11-22T09:04:11.0288582Z --- End of stack trace from previous location ---
2023-11-22T09:04:11.0289540Z    at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext context)
2023-11-22T09:04:11.0290880Z    at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
2023-11-22T09:04:11.0291902Z --- End of stack trace from previous location ---
2023-11-22T09:04:11.0293245Z    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
2023-11-22T09:04:11.0294320Z --- End of stack trace from previous location ---
2023-11-22T09:04:11.0295258Z    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
2023-11-22T09:04:11.0296245Z --- End of stack trace from previous location ---
2023-11-22T09:04:11.0297239Z    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
2023-11-22T09:04:11.0298270Z --- End of stack trace from previous location ---
2023-11-22T09:04:11.0299396Z    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
2023-11-22T09:04:11.0300436Z --- End of stack trace from previous location ---
2023-11-22T09:04:11.0301360Z    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
2023-11-22T09:04:11.0302335Z --- End of stack trace from previous location ---
2023-11-22T09:04:11.0303322Z    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
2023-11-22T09:04:11.0307825Z --- End of stack trace from previous location ---
2023-11-22T09:04:11.0308798Z    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
2023-11-22T09:04:11.0309806Z --- End of stack trace from previous location ---
2023-11-22T09:04:11.0310802Z    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
2023-11-22T09:04:11.0315696Z ##[error]Process completed with exit code 1.
2023-11-22T09:04:11.0562877Z Cleaning up orphan processes
```
Are you able to see why the terminating error occurs? I have also tried with a different template.

**Comment by kamil-mrzyglod** [comment]
I see you're passing `https://raw.githubusercontent.com/{placeholder}/{placeholder}` as template URL - should those placeholders be replaced by some value you're providing?

**Comment by BenjaminEngeset** [comment]
> Hey @BenjaminEngeset, it seems that template passed to the workflow returns 404. Speaking about the URL from the log - https://raw.githubusercontent.com/xxx/xxx/benjaminengeset/test-module/modules/operationalinsights/workspaces/test/main.test.json

The xxx are placeholders here as the repository is hosted in GitHub enterprise cloud as an internal repo. I have manually removed the values and inserted `xxx`. As you can tell when doing ls:

```
2023-11-22T09:04:10.7017781Z -rw-r--r-- 1 runner docker       14 Nov 22 09:04 main.test.json
```
So it has successfully curled.

Also by piping to jq for checking syntax errors, nothing is emitted, which means no syntax errors.
 ```
2023-11-22T09:04:10.7062799Z �[36;1mmain.test.json | jq .�[0m
```

**Comment by BenjaminEngeset** [comment]
> I see you're passing `https://raw.githubusercontent.com/{placeholder}/{placeholder}` as template URL - should those placeholders be replaced by some value you're providing?

I have manually removed the original values here as well as it's an internal repo within my organization.

**Comment by kamil-mrzyglod** [comment]
> > Hey @BenjaminEngeset, it seems that template passed to the workflow returns 404. Speaking about the URL from the log - https://raw.githubusercontent.com/xxx/xxx/benjaminengeset/test-module/modules/operationalinsights/workspaces/test/main.test.json
> 
> The xxx are placeholders here as the repository is hosted in GitHub enterprise cloud as an internal repo. I have manually removed the values and inserted `xxx` so I don't expose my company. As you can tell when doing ls:
> 
> ```
> 2023-11-22T09:04:10.7017781Z -rw-r--r-- 1 runner docker       14 Nov 22 09:04 main.test.json
> ```
> 
> So it has successfully curled.
> 
> Also by piping to jq for checking syntax errors, nothing is emitted, which means no syntax errors.
> 
> ```
> 2023-11-22T09:04:10.7062799Z �[36;1mmain.test.json | jq .�[0m
> ```

I don't think such script works correctly. I can run it locally getting `command not found: main.test.json`. To run it properly, I could go for `cat main.test.json | jq .` what indeed returns an error `jq: parse error: Expected string key before ':' at line 1, column 4`.

My feeling is that instead of downloading a file, you saved `404:NotFound` as `main.test.json`. You can reproduce it by running:
```
curl -O https://raw.githubusercontent.com/xxx/xxx/benjaminengeset/test-module/modules/operationalinsights/workspaces/test/main.test.json
```
ACE also tells you what's the content of the file:
```
2023-11-22T09:04:11.0176510Z [Error] Couldn't parse the following template - 404:NotFound
```
That `404:NotFound` is exactly what ACE got from the template you passed.

**Comment by BenjaminEngeset** [comment]
> > > Hey @BenjaminEngeset, it seems that template passed to the workflow returns 404. Speaking about the URL from the log - https://raw.githubusercontent.com/xxx/xxx/benjaminengeset/test-module/modules/operationalinsights/workspaces/test/main.test.json
> > 
> > 
> > The xxx are placeholders here as the repository is hosted in GitHub enterprise cloud as an internal repo. I have manually removed the values and inserted `xxx` so I don't expose my company. As you can tell when doing ls:
> > ```
> > 2023-11-22T09:04:10.7017781Z -rw-r--r-- 1 runner docker       14 Nov 22 09:04 main.test.json
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > So it has successfully curled.
> > Also by piping to jq for checking syntax errors, nothing is emitted, which means no syntax errors.
> > ```
> > 2023-11-22T09:04:10.7062799Z �[36;1mmain.test.json | jq .�[0m
> > ```
> 
> I don't think such script works correctly. I can run it locally getting `command not found: main.test.json`. To run it properly, I could go for `cat main.test.json | jq .` what indeed returns an error `jq: parse error: Expected string key before ':' at line 1, column 4`.
> 
> My feeling is that instead of downloading a file, you saved `404:NotFound` as `main.test.json`. You can reproduce it by running:
> 
> ```
> curl -O https://raw.githubusercontent.com/xxx/xxx/benjaminengeset/test-module/modules/operationalinsights/workspaces/test/main.test.json
> ```
> 
> ACE also tells you what's the content of the file:
> 
> ```
> 2023-11-22T09:04:11.0176510Z [Error] Couldn't parse the following template - 404:NotFound
> ```
> 
> That `404:NotFound` is exactly what ACE got from the template you passed.

Thanks @kamil-mrzyglod. I'm laughing, I cannot understand that I haven't seen that I'm basically saving a file with the error code. I'm truly grateful for your help on this one.

I just have to figure out why the 404 is emitted when the directory is correct and the reusable workflow has been given read permission onto the repo.

**Comment by BenjaminEngeset** [comment]
> If you replace `xxx` with proper value, are you able to open the template in your browser?

Not directly by the URL I'm passing onto the reusable workflow and ACE. Then I get the same error code emitted as the `Prepare/Check Arm Assets` step is getting. This is the URL:

`https://raw.githubusercontent.com/MyCompany/bicep-registry-modules-test/benjaminengeset/test-module/modules/operationalinsights/workspaces/test/main.test.json`

![image](https://github.com/TheCloudTheory/arm-estimator/assets/99641908/3f28d45e-682d-4ef0-be2c-d69f555ebc7a)

However, if I browse the directory and find the file in GitHub:

![image](https://github.com/TheCloudTheory/arm-estimator/assets/99641908/2b8f8c08-5a8b-4b8f-a55d-7c9bba43bd3c)

Then press raw I get the template.

The URL is then:

`https://raw.githubusercontent.com/MyCompany/bicep-registry-modules-test/benjaminengeset/test-module/modules/operationalinsights/workspaces/test/main.test.json?token=GHSAT0AAAAAACGxxx`

Perhaps it's not so weird that the reusable workflow cannot access the template with:

```
permissions:
  contents: read
```

As neither I get the token I need by accessing the URL... Hm..

**Comment by kamil-mrzyglod** [comment]
So that's unfortunate and maybe whole scenario is not supported (fetching a private files over HTTP request from GitHub). Maybe it should be performed to other way - by providing an action for GitHub workflow to download ACE and run based on a set of provided parameters. Then you'd be able to run estimation directly in your repo by using an action. 

Thoughts? :)

**Comment by BenjaminEngeset** [comment]
> So that's unfortunate and maybe whole scenario is not supported (fetching a private files over HTTP request from GitHub). Maybe it should be performed to other way - by providing an action for GitHub workflow to download ACE and run based on a set of provided parameters. Then you'd be able to run estimation directly in your repo by using an action.
> 
> Thoughts? :)

After some research I can conclude with that it's not supported. What I have done for now, which is working, is to create a fine-granulated personal access token. I'm passing this into the reusable workflow as a secret and consuming it in the `Prepare/Check Arm Assets` step.

I'll do some more testing and optimization before opening a PR with this option available for private repositories now, as well with the different statements to handle the various situations with parameters.

I think definitely the best option here would to have ACE as an action in the marketplace. This would probably put some effort towards you, but it will worth it no doubt. It also makes it much better from an consumer standpoint.

Thanks for all the great help so far, truly grateful once again!

**Comment by kamil-mrzyglod** [comment]
Thanks! So it seems I'll continue with creating a dedicated GitHub Action for ACE in order to address the issue you faces. Is it okay to close this issue?

**Comment by BenjaminEngeset** [comment]
Yes @kamil-mrzyglod!
