### ISSUE TITLE
Error when calculating Application Insights

### ISSUE THREAD

**Issue by kamil-mrzyglod** [TheCloudTheory/arm-estimator#230]
When performing an estimation, ACE fails with the following error:
```
Unhandled exception: System.MissingMethodException: Constructor on type 'ApplicationInsightsEstimationCalculation' not found.
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at ACE.WhatIf.WhatIfProcessor.Calculate[TQuery,TCalculation](WhatIfChange change, CommonResourceIdentifier id, CancellationToken token, Nullable`1 useFakeApiResponse) in /home/runner/work/arm-estimator/arm-estimator/arm-estimator/WhatIf/WhatIfProcessor.cs:line 575
   at ACE.WhatIf.WhatIfProcessor.Process(CancellationToken token) in /home/runner/work/arm-estimator/arm-estimator/arm-estimator/WhatIf/WhatIfProcessor.cs:line 222
   at ACE.Program.Estimate(FileInfo templateFile, String scopeId, String resourceGroupName, String location, EstimateOptions options, CommandType commandType) in /home/runner/work/arm-estimator/arm-estimator/arm-estimator/Program.cs:line 343
   at ACE.Program.<>c.<<Main>b__2_23>d.MoveNext() in /home/runner/work/arm-estimator/arm-estimator/arm-estimator/Program.cs:line 125
--- End of stack trace from previous location ---
   at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()

```

**Comment by kamil-mrzyglod** [comment]
Fixed in #231
