### ISSUE TITLE
Unhandled exception: System.MissingMethodException: Constructor on type 'StorageAccountEstimationCalculation' not found

### ISSUE THREAD

**Issue by reijoh** [TheCloudTheory/arm-estimator#244]
Trying to run this in a GitHub action.

## About environment

- Operating System: Ubuntu 22.04.3 LTS
- Runner Image: ubuntu-22.04 version 20231217.2.0
- Included Software: <https://github.com/actions/runner-images/blob/ubuntu22/20231217.2/images/ubuntu/Ubuntu2204-Readme.md>
- Image Release: <https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20231217.2>

## GitHub Action

```yaml
name: Azure Cost
on:
  workflow_dispatch:
jobs:
  cost:
    - name: Checkout head ref (src)
      id: checkout_src
      uses: actions/checkout@v4
      with:
        persist-credentials: false
        fetch-depth: 1

    - name: Log in to Azure (Federated)
      id: login_open_id
      uses: azure/login@v1
      with:
        client-id: cccc11b1-67af-474b-ac4a-67ee18414df1 
        tenant-id: aaaa11b1-67af-474b-ac4a-67ee18414df1 
        subscription-id: bbbb11b1-67af-474b-ac4a-67ee18414df1 

    - name: Estimate cost
      run: |
        curl -o linux-x64.zip -sSL https://github.com/TheCloudTheory/arm-estimator/releases/download/1.3/linux-x64.zip
        unzip -q linux-x64.zip
        chmod +x ./azure-cost-estimator
        ./azure-cost-estimator sub main.json bbbb11b1-67af-474b-ac4a-67ee18414df1 westeurope --parameters main.parameters.json --disableDetailedMetrics --generateJsonOutput --jsonOutputFilename cost_output.json
```

## Result

```text
                                              .***      ***                                         
                                   ,    ***.********,****                                           
                                     **********************                                         
                               *    ************. ***********  *                                    
                             ///   *******, ****  ////////////******                                
                               .//************ ///// /////////********                              
                           ///////// ********///////// //////.********    (,                        
                     .   ///////////// **** ////////////,////******* ( (/                           
                       *////////////////   ////////////////  ** ((((((((((((                        
                        ///,  */////////.   **************,    ((((((((((((((                       
                       ///////////////.(((((((,******** ///// (((((( (((((((((                      
                       ///////////// ((((((((((((   ////////// ((((((((((*((((                      
                        ////////// ((((((((((( ((    //////////(((((((((((((((                      
                    //   /////// (((((( (((((((((((((((( ///////(((((((((((((                       
                       //   /  ( ((((((((((((((((,((((((((((.////(((((((((  ((                      
                                                                                                    
                                  ACE (Azure Cost Estimator) [1.3]

General help: https://github.com/TheCloudTheory/arm-estimator/discussions
Bugs & issues: https://github.com/TheCloudTheory/arm-estimator/issues

------------------------------

Run configuration:

-> Scope: Subscription
-> Susbcription Id: ceac59a3-67af-474b-ac4a-67ee18414df1
-> Template file: main.json
-> Deployment mode: Incremental
-> Threshold: Not Set
-> Parameters file: main.parameters.json
-> Currency: USD
-> Generate JSON output: True
-> Silent mode: False
-> Redirect stdout: False
-> Disabled detailed metrics: True
-> Generate HTML output: False
-> HTML output filename: Not Set
-> Dry run enabled: False
-> Cache disabled: False
-> Cache handler: Local
-> Conversion rate: 1
-> Webhook URL: Disabled

------------------------------

What If status:

-> Cache miss for What If data.
-> Waiting for response from What If API.
-> Saving What If response to cache.
-> Detected 2 resources.

[NoChange] ttstsp3 [Microsoft.Resources/resourceGroups]
[Modify] ttstsp3018 [Microsoft.Storage/storageAccounts]

-------------------------------

Estimations:

Unhandled exception: System.MissingMethodException: Constructor on type 'StorageAccountEstimationCalculation' not found.
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at ACE.WhatIf.WhatIfProcessor.Calculate[TQuery,TCalculation](WhatIfChange change, CommonResourceIdentifier id, CancellationToken token, Nullable`1 useFakeApiResponse) in /home/runner/work/arm-estimator/arm-estimator/arm-estimator/WhatIf/WhatIfProcessor.cs:line 575
   at ACE.WhatIf.WhatIfProcessor.Process(CancellationToken token) in /home/runner/work/arm-estimator/arm-estimator/arm-estimator/WhatIf/WhatIfProcessor.cs:line 181
   at ACE.Program.Estimate(FileInfo templateFile, String scopeId, String resourceGroupName, String location, EstimateOptions options, CommandType commandType) in /home/runner/work/arm-estimator/arm-estimator/arm-estimator/Program.cs:line 343
   at ACE.Program.<>c.<<Main>b__2_23>d.MoveNext() in /home/runner/work/arm-estimator/arm-estimator/arm-estimator/Program.cs:line 125
--- End of stack trace from previous location ---
   at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

## Template

[main.json](https://github.com/TheCloudTheory/arm-estimator/files/13877301/main.json)
[main.parameters.json](https://github.com/TheCloudTheory/arm-estimator/files/13877302/main.parameters.json)

**Comment by kamil-mrzyglod** [comment]
Could you please check if the action works for you for `0.0.12-preview` version?

**Comment by reijoh** [comment]
> Could you please check if the action works for you for `0.0.12-preview` version?

Amazing work, it did indeed succeed now, here is the output:

Command used: ./azure-cost-estimator sub main.json bbbb11b1-67af-474b-ac4a-67ee18414df1 westeurope --parameters main.parameters.json --disableDetailedMetrics --disable-cache --generateJsonOutput --currency EUR --threshold -1 --jsonOutputFilename cost_output.json

```text
                                                                                                   
                                              .***      ***                                         
                                   ,    ***.********,****                                           
                                     **********************                                         
                               *    ************. ***********  *                                    
                             ///   *******, ****  ////////////******                                
                               .//************ ///// /////////********                              
                           ///////// ********///////// //////.********    (,                        
                     .   ///////////// **** ////////////,////******* ( (/                           
                       *////////////////   ////////////////  ** ((((((((((((                        
                        ///,  */////////.   **************,    ((((((((((((((                       
                       ///////////////.(((((((,******** ///// (((((( (((((((((                      
                       ///////////// ((((((((((((   ////////// ((((((((((*((((                      
                        ////////// ((((((((((( ((    //////////(((((((((((((((                      
                    //   /////// (((((( (((((((((((((((( ///////(((((((((((((                       
                       //   /  ( ((((((((((((((((,((((((((((.////(((((((((  ((                      
                                                                                                    
                                  ACE (Azure Cost Estimator) [1.4-beta1]

General help: https://github.com/TheCloudTheory/arm-estimator/discussions
Bugs & issues: https://github.com/TheCloudTheory/arm-estimator/issues

------------------------------

Run configuration:

-> Scope: Subscription
-> Susbcription Id: ceac59a3-67af-474b-ac4a-67ee18414df1
-> Template file: main.json
-> Deployment mode: Incremental
-> Threshold: Not Set
-> Parameters file: main.parameters.json
-> Currency: EUR
-> Generate JSON output: True
-> Silent mode: False
-> Redirect stdout: False
-> Disabled detailed metrics: True
-> Generate HTML output: False
-> HTML output filename: Not Set
-> Dry run enabled: False
-> Cache disabled: True
-> Cache handler: Disabled
-> Conversion rate: 1
-> Webhook URL: Disabled

------------------------------

What If status:

-> Cache is disabled.
-> Waiting for response from What If API.
-> Detected 2 resources.

[NoChange] ttstsp3 [Microsoft.Resources/resourceGroups]
[Modify] ttstsp3018 [Microsoft.Storage/storageAccounts]

-------------------------------

Estimations:

[Modify] ttstsp3018
   \--- Type: Microsoft.Storage/storageAccounts
   \--- Location: EU West
   \--- Total cost: 0.12 EUR
   \--- Delta: 0.00 EUR

-------------------------------

Free resources:

[NoChange] ttstsp3
   \--- Type: Microsoft.Resources/resourceGroups


-------------------------------

Summary:

-> Total cost: 0.12 EUR
-> Delta: +0.00 EUR

-> Generating JSON output file as cost_output.json.json
```

**Comment by kamil-mrzyglod** [comment]
Great, happy it solved the problem :)
