### ISSUE TITLE
Passing bicepparam fails 

### ISSUE THREAD

**Issue by riosengineer** [TheCloudTheory/arm-estimator#267]
Hey, 

If I try and pass a `.bicepparam` file like `--parameters some.bicepparam` the Azure DevOps pipeline will fail: 

```
Unhandled exception: System.Text.Json.JsonException: 'u' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: 'u' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at ACE.EstimatePayloadProperties..ctor(String template, DeploymentMode deploymentMode, String parameters) in /home/runner/work/arm-estimator/arm-estimator/arm-estimator/EstimatePayload.cs:line 35
   at ACE.EstimatePayload..ctor(String template, DeploymentMode deploymentMode, String parameters) in /home/runner/work/arm-estimator/arm-estimator/arm-estimator/EstimatePayload.cs:line 15
   at ACE.WhatIf.AzureWhatIfHandler.SendInitialRequest() in /home/runner/work/arm-estimator/arm-estimator/arm-estimator/WhatIf/AzureWhatIfHandler.cs:line 126
   at ACE.WhatIf.AzureWhatIfHandler.GetResponseWithRetries() in /home/runner/work/arm-estimator/arm-estimator/arm-estimator/WhatIf/AzureWhatIfHandler.cs:line 73
   at ACE.WhatIf.WhatIfParser.GetWhatIfData() in /home/runner/work/arm-estimator/arm-estimator/arm-estimator/WhatIf/WhatIfParser.cs:line 58
   at ACE.Program.Estimate(FileInfo templateFile, String scopeId, String resourceGroupName, String location, EstimateOptions options, CommandType commandType) in /home/runner/work/arm-estimator/arm-estimator/arm-estimator/Program.cs:line 250
   at ACE.Program.<>c.<<Main>b__1_15>d.MoveNext() in /home/runner/work/arm-estimator/arm-estimator/arm-estimator/Program.cs:line 65
--- End of stack trace from previous location ---
   at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

If I convert my bicepparam back to `.json` and pass it into the task like `--parameter param.json` it works fine. 

ADO Tasks:

```yaml
jobs:
- job: RunNoCache
  displayName: Bicep Estimator
  steps:
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        wget https://github.com/TheCloudTheory/arm-estimator/releases/download/1.2-beta2/ace-linux-x64.zip
        unzip ace-linux-x64.zip
        chmod +x ./azure-cost-estimator
  - task: AzureCLI@2
    displayName: Bicep Cost Estimation
    inputs:
      azureSubscription: 'sc-msdn'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        ./azure-cost-estimator main.bicep 1417db09-accd-4799-b224-4346e5cb12c3 bicep-estimator --parameters main.bicepparam --currency GBP --generateHtmlOutput --htmlOutputFilename bicep-cost --outputFormat Table
```

I have checked the Wiki and to be honest, it seems pretty clear you should be able to just pass the `bicepparam` in the `--parameters` switch. If I run a what-if locally with my bicepparam it works correctly.

Am I missing something or is this potentially a bug?

Thank you!

**Comment by riosengineer** [comment]
Ok, I am an idiot :)  The docs have v1.2 in the example, and I didn't realise until looking closer.....

**Comment by riosengineer** [comment]
@kamil-mrzyglod I don't think the Wiki is in GIT so I can't contribute to help you out :). 

I was going to amend these two pages:

https://github.com/TheCloudTheory/arm-estimator/wiki/Support-for-%60.bicepparam%60 (typo 'bieparam' insetad of 'bicepparam') 
https://github.com/TheCloudTheory/arm-estimator/wiki/Installation - I was going to update this for latest stable release like: 

```yaml
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        wget https://github.com/TheCloudTheory/arm-estimator/releases/download/v1.5-beta2/linux-x64.zip
        unzip linux-x64.zip
        chmod +x ./azure-cost-estimator
```

**Comment by kamil-mrzyglod** [comment]
@riosengineer Hey, thanks for pointing that out! I'll incorporate those changes into the wiki :)
