### ISSUE TITLE
[Request] Add support for P0V3 App Service Plan

### ISSUE THREAD

**Issue by riosengineer** [TheCloudTheory/arm-estimator#269]
Hey @kamil-mrzyglod, is there any on going updates that may add this particular SKU, or in general, more supported types/skus across Azure for the arm-estimator project? I am not proficient in #C so I think I would struggle to contribute otherwise I would!

`[Warning] asp-test (Microsoft.Web/serverfarms) [SKU is not yet supported - P0V3]`

Would be great to get this one !

**Comment by kamil-mrzyglod** [comment]
Hey, I currently support the project on a per-request basis, if adding that SKU is going to help you, then I'm happy to add it over the weekend :)

**Comment by riosengineer** [comment]
> Hey, I currently support the project on a per-request basis, if adding that SKU is going to help you, then I'm happy to add it over the weekend :)

That would be awesome. We use this SKU a lot, as it's the cheapest premium production SKU. That would be helpful. Thank you Kamil!

**Comment by kamil-mrzyglod** [comment]
@riosengineer feel free to test with `1.5` release.

**Comment by riosengineer** [comment]
> @riosengineer feel free to test with `1.5` release.

Strangely, if I use v1.5 I get an error about my params failing validation, but if I roll back to v1.5-beta2 it works fine. 

```
  "code": "InvalidTemplate",
  "message": "Deployment template validation failed: \u0027The value for the template parameter \u0027tags\u0027 at line \u00271\u0027 and column \u0027242\u0027 is not provided. Please see https://aka.ms/arm-create-parameter-file for usage details.\u0027.",
  "details": null
}
Unhandled exception: System.Exception: An error happened when performing WhatIf operation.
   at ACE.Program.<>c.<<Main>b__2_1>d.MoveNext() in /home/runner/work/arm-estimator/arm-estimator/ace/Program.cs:line 139
--- End of stack trace from previous location ---
   at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.AnonymousCommandHandler.SyncUsingAsync(InvocationContext context)
   at System.CommandLine.Invocation.AnonymousCommandHandler.Invoke(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

**Comment by kamil-mrzyglod** [comment]
@riosengineer may I ask you to report a bug with all the details, so I can take a look?
