### ISSUE TITLE
v1.5 fails with template error but previous versions work

### ISSUE THREAD

**Issue by riosengineer** [TheCloudTheory/arm-estimator#271]
Hey Kamil, 

When trying to use the latest release, I get an error: 

```text
What If status:

-> Cache miss for What If data.
-> Waiting for response from What If API.
-> Saving What If response to cache.
[Error] An error happened when performing WhatIf operation.
[Error] {
  "code": "InvalidTemplate",
  "message": "Deployment template validation failed: \u0027The value for the template parameter \u0027resourceLocation\u0027 at line \u00271\u0027 and column \u0027180\u0027 is not provided. Please see https://aka.ms/arm-create-parameter-file for usage details.\u0027.",
  "details": null
}
Unhandled exception: System.Exception: An error happened when performing WhatIf operation.
   at ACE.Program.<>c.<<Main>b__2_1>d.MoveNext() in /home/runner/work/arm-estimator/arm-estimator/ace/Program.cs:line 139
--- End of stack trace from previous location ---
   at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.AnonymousCommandHandler.SyncUsingAsync(InvocationContext context)
   at System.CommandLine.Invocation.AnonymousCommandHandler.Invoke(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

However, what is interesting, is that if I roll back my task to v1.5-beta2 or any previous version, and rerun the pipeline task - it will be fine. 

The templates it is scanning against are the same. I have also verified I can run a manual `what-if` in my CLI terminal OK for these also, and it is successful.

Let me know if you need any other info!

**Comment by kamil-mrzyglod** [comment]
Hey @riosengineer!

Would it be possible to provide:
* full command you're running
* Bicep code (param definition will suffice)

**Comment by riosengineer** [comment]
> Hey @riosengineer!
> 
> Would it be possible to provide:
> 
> * full command you're running
> * Bicep code (param definition will suffice)

Running this task, but I'll switch the `wget` url between the latest and older versions to test the bicep file.
```yaml
jobs:
- job: RunNoCache
  displayName: Bicep Estimator
  steps:
  - checkout: self
    fetchDepth: 0
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        wget https://github.com/TheCloudTheory/arm-estimator/releases/download/v1.5/linux-x64.zip
        unzip linux-x64.zip
        chmod +x ./azure-cost-estimator
      workingDirectory: $(System.DefaultWorkingDirectory)
```

The bicep code may be more challenging, as it's a corporate template. Do you need the actual `main.bicep` template, or just the `bicepparam` file? Thanks

**Comment by riosengineer** [comment]
`bicepparam` obfuscated

```bicep
using '../main.bicep'

param tags = {
    Application: 'SomeApp'
    CostCenter: 'CC'
    Creator: 'Rios Engineer'
    DeploymentMethod: 'Bicep'
    Entity: 'Contoso'
    Environment: 'Prod'
}


// Shared Components
param sharedSubId = 'someGuid'
param privateDnsZoneRgName = 'rg-uks-shared'
param privateDnsZoneName = 'privatelink.azurewebsites.net'
param privateDnsZoneNameAppConf = 'privatelink.azconfig.io'
param privateDnsZoneNameKv = 'privatelink.vaultcore.azure.net'
param privateDnsZoneNameBlob = 'privatelink.blob.core.windows.net'
// 

param env = 'prd'
param app = 'appName'
param vnetName = 'vnet-uks-prd'
param kvName = 'kv-uks-prd'
param appInsightsName = 'appi-uks-prd'
param lawName = 'log-uks-prd'
param appPlanName = 'asp-uks-prd'
param nsgName = 'nsg-uks-prd'
param nsgPeName = 'nsg-uks-prd'
param storageAccountName = 'ssomestorageprd'
param appPlanSkuName = 'P0V3'
param funcName = 'func-uks-prd'
param appConfName = 'ac-uks-prd'
param appConfigSku = 'Standard'
param kvSku = 'standard'
param vnetPrefix = '10.1.0.0/24'
param integrationSubnetName = 'sn-uks-prd-integrations'
param integrationSubnetPrefix = '10.0.0.0/27'
param peSubnetName = 'sn-uks-prd-pe'
param peSubnetPrefix = '10.1.0.0/27'
```

Main param definitions:

```bicep
param timeNow string = utcNow('yyyy-MM-ddTHH:mm')

@description('The tags for all resources')
param tags object

@allowed([
  'dev'
  'tst'
  'prd'
])
@description('The name of the environment')
param env string

@description('The name of the application / project')
param app string

@description('The name of the virtual network')
param vnetName string

@description('The name of the key vault')
param kvName string

@description('The name of the application insights')
param appInsightsName string

@description('The name of the log analytics workspace')
param lawName string

@description('The name of the server farm aka app plan')
param appPlanName string

@description('The name of the network security group')
param nsgName string

@description('The name of the network security group private endpoint')
param nsgPeName string

@description('The SKU for the server farm')
param appPlanSkuName string

@description('Storage Account resource name')
param storageAccountName string

@description('The name of the Function app')
param funcName string

@description('The name of the application configuration for Function App')
param appConfName string

@description('The SKU for the application configuration')
param appConfigSku string

@description('Azure resource deployment location')
param location string = resourceGroup().location

@description('The name of the key vault')
param kvSku string

@description('The subscription ID of the private DNS Zone')
param sharedSubId string

@description('The name of the private DNS Zone')
param privateDnsZoneRgName string

@description('The name of the Function private DNS Zone')
param privateDnsZoneName string

@description('The name of the Key Vault private DNS Zone')
param privateDnsZoneNameKv string

@description('The name of the App Config private DNS Zone')
param privateDnsZoneNameAppConf string

@description('The name of the Storage Account blob private DNS Zone')
param privateDnsZoneNameBlob string

@description('The name of the Storage Account file private DNS Zone')
param privateDnsZoneNameFile string

@description('The subnet prefix for the private endpoint')
param peSubnetPrefix string

@description('The integration subnet prefix')
param integrationSubnetPrefix string

@description('The address prefix for the virtual network')
param vnetPrefix string

@description('The name of the integration subnet')
param integrationSubnetName string

@description('The name of the private endpoint subnet')
param peSubnetName string
```

How's this @kamil-mrzyglod ?

**Comment by kamil-mrzyglod** [comment]
@riosengineer Thanks! I don't see the definition for `resourceLocation` param and its value in the `bicepparam` file. Could you please clarify where is it defined?

**Comment by riosengineer** [comment]
> @riosengineer Thanks! I don't see the definition for `resourceLocation` param and its value in the `bicepparam` file. Could you please clarify where is it defined?

```param location string = resourceGroup().location``` it grabs it from the resource group location that is already created. My what-if locally works `az deployment group what-if -g bicep-estimator -f main.bicep -p prod.bicepparam`

**Comment by kamil-mrzyglod** [comment]
@riosengineer sure, but the error returned from the API states:
```
Deployment template validation failed: \u0027The value for the template parameter \u0027resourceLocation\u0027 at line \u00271\u0027 and column \u0027180\u0027 is not provided. Please see https://aka.ms/arm-create-parameter-file for usage details.\u0027.
```
It looks like the template requires `resourceLocation` parameter which isn't provided. Are you sure the correct template is being provided to ACE?

**Comment by riosengineer** [comment]
> @riosengineer sure, but the error returned from the API states:
> 
> ```
> Deployment template validation failed: \u0027The value for the template parameter \u0027resourceLocation\u0027 at line \u00271\u0027 and column \u0027180\u0027 is not provided. Please see https://aka.ms/arm-create-parameter-file for usage details.\u0027.
> ```
> 
> It looks like the template requires `resourceLocation` parameter which isn't provided. Are you sure the correct template is being provided to ACE?

I'm pretty sure, I have the pipeline echo the file and param file it is about to use in ACE and it shows the two I am expecting. I actually just amended the template so to include the resource location param but it still fails with that error. 

I am running it for two others files, and they have a different API response but it's the same stack trace error: 

```text
[Error] {
  "code": "InvalidTemplate",
  "message": "Deployment template validation failed: \u0027The value for the template parameter \u0027tags\u0027 at line \u00271\u0027 and column \u0027242\u0027 is not provided. Please see https://aka.ms/arm-create-parameter-file for usage details.\u0027.",
  "details": null
}```

So I removed the tags object just to test, and when I re-run it just moves onto another param:

```text 
[Error] {
  "code": "InvalidTemplate",
  "message": "Deployment template validation failed: \u0027The value for the template parameter \u0027env\u0027 at line \u00271\u0027 and column \u0027241\u0027 is not provided. Please see https://aka.ms/arm-create-parameter-file for usage details.\u0027.",
  "details": null
}```

But if I use any older version, all is OK - it's strange. They compile on with `bicep build`  and also just got an OK response when running `az group validate` to validate the template to ARM ` "provisioningState": "Succeeded",`

I'll try and do more tests to help identify some pattern but I'm pretty sure the templates are ok.

**Comment by kamil-mrzyglod** [comment]
Thanks, will check the test suite, maybe there are false positives.

**Comment by kamil-mrzyglod** [comment]
@riosengineer One more request - could you please paste the full output from ACE when you run the command? I need to check if it's using Bicep CLI or Azure CLI. Is this a managed runner? If so, it may be the same issue I saw in my pipelines.

**Comment by riosengineer** [comment]
> @riosengineer One more request - could you please paste the full output from ACE when you run the command? I need to check if it's using Bicep CLI or Azure CLI. Is this a managed runner? If so, it may be the same issue I saw in my pipelines.

It is a hosted ADO runner, I use the Azure CLI task, see below:


```text
Starting: AzureCLI
==============================================================================
Task         : Azure CLI
Description  : Run Azure CLI commands against an Azure subscription in a PowerShell Core/Shell script when running on Linux agent or PowerShell/PowerShell Core/Batch script when running on Windows agent.
Version      : 2.244.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/azure-cli
==============================================================================
/usr/bin/az --version
azure-cli                         2.63.0

core                              2.63.0
telemetry                          1.1.0

Extensions:
azure-devops                       1.0.1

Dependencies:
msal                              1.30.0
azure-mgmt-resource               23.1.1

Python location '/opt/az/bin/python3'
Extensions directory '/opt/az/azcliextensions'

Python (Linux) 3.11.8 (main, Jul 31 2024, 03:39:39) [GCC 11.4.0]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.
Setting AZURE_CONFIG_DIR env variable to: /home/vsts/work/_temp/.azclitask
Setting active cloud to: AzureCloud
/usr/bin/az cloud set -n AzureCloud
/usr/bin/az login --service-principal -u *** --tenant REDACTED --allow-no-subscriptions --federated-token ***
[
  {
    "cloudName": "AzureCloud",
    "homeTenantId": "REDACTED",
    "id": "REDACTED",
    "isDefault": true,
    "managedByTenants": [],
    "name": "REDACTED",
    "state": "Enabled",
    "tenantId": "REDACTED",
    "user": {
      "name": "***",
      "type": "servicePrincipal"
    }
  }
]
/usr/bin/az account set --subscription REDACTED
/usr/bin/pwsh -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command . '/home/vsts/work/_temp/azureclitaskscript1724944576387.ps1'

------------------------------

New version of ACE is available. Current version: 1.5+ec80068943fe61d5d41535e1758a35e75b1effd4, latest version: 1.5
Please update ACE to the latest version.

------------------------------

Run configuration:

-> Scope: ResourceGroup
-> Susbcription Id: REDACTED
-> Resource group: bicep-estimator
-> Template file: REDACTED
-> Deployment mode: Incremental
-> Threshold: 
-> Parameters file: prod.bicepparam
-> Currency: GBP
-> Generate JSON output: False
-> Silent mode: False
-> Redirect stdout: False
-> Disabled detailed metrics: False
-> Generate HTML output: False
-> HTML output filename: Not Set
-> Dry run enabled: False
-> Cache disabled: False
-> Cache handler: Local
-> Conversion rate: 1
-> Webhook URL: Disabled

------------------------------

-> Attempting to compile Bicep file using Bicep CLI.
-> Compilation completed!

------------------------------

-> Attempting to compile Bicepparam file using Bicep CLI.
-> Compilation completed!

------------------------------

What If status:

-> Cache miss for What If data.
-> Waiting for response from What If API.
-> Saving What If response to cache.
[Error] An error happened when performing WhatIf operation.
[Error] {
  "code": "InvalidTemplate",
  "message": "Deployment template validation failed: \u0027The value for the template parameter \u0027resourceLocation\u0027 at line \u00271\u0027 and column \u0027180\u0027 is not provided. Please see https://aka.ms/arm-create-parameter-file for usage details.\u0027.",
  "details": null
}
```

**Comment by kamil-mrzyglod** [comment]
@riosengineer I think I managed to reproduce the error. It seems it's caused by Bicep CLI compilation which generates different schema for parameters than Azure CLI. I'll check what kind of workaround or fix will mitigate the issue for you.

**Comment by riosengineer** [comment]
> @riosengineer I think I managed to reproduce the error. It seems it's caused by Bicep CLI compilation which generates different schema for parameters than Azure CLI. I'll check what kind of workaround or fix will mitigate the issue for you.

Good to know you could replicate it. Hopefully not too much trouble. Thank you for your work!

**Comment by riosengineer** [comment]
> Deployment template validation failed: \u0027The value for the template parameter \u0027resourceLocation

Works perfectly! Legend! Thanks Kamil. One more, what's the markdown output syntax? `--generateMarkdownOutput true`?

**Comment by kamil-mrzyglod** [comment]
@riosengineer `--generate-markdown-output` and `--markdown-output-filename`, I'll add them to the Wiki soon.
